<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Guinevere</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <!-- NuGet Package Properties -->
        <Title>Guinevere</Title>
        <PackageId>MASS4.Guinevere</PackageId>
        <Description>A GPU accelerated immediate mode GUI system built on SkiaSharp. Provides high-performance rendering with modern graphics APIs support.</Description>
        <Company>MASS4</Company>
        <Product>Guinevere</Product>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Version>5.4.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
        <PackageReference Include="SkiaSharp" Version="4.152.1" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.152.1" />
        <PackageReference Include="SkiaSharp.Views.Desktop.Common" Version="4.152.1" />
        <PackageReference Include="SkiaSharp.Vulkan.SharpVk" Version="4.152.1" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Layout\Scope\LayoutNodeScopeValueIconFont.cs" />
        <Compile Remove="Layout\Scope\LayoutNodeScopeValueFontSize.cs" />
        <Compile Remove="Layout\Scope\LayoutNodeScopeValueFontColor.cs" />
        <Compile Remove="Layout\Scope\LayoutNodeScopeValueFont.cs" />
        <Compile Remove="Layout\Scope\LayoutNodeScopeValue.cs" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Layout\Scope\" />
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="Guinevere.Tests" />
        <InternalsVisibleTo Include="Guinevere.Excalibur" />
    </ItemGroup>

</Project>
